version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/Fiestivo
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: fiestivo_db
      POSTGRES_USER: fiestivo_user
      POSTGRES_PASSWORD: secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
